Update android workflow

diff --git a/.github/workflows/e2e-android2.yaml b/.github/workflows/e2e-android2.yaml
--- a/.github/workflows/e2e-android2.yaml
+++ b/.github/workflows/e2e-android2.yaml
@@ -30,19 +30,44 @@ jobs:
           distribution: 'temurin'
           java-version: '17'
 
-      - name: Gradle cache
-        uses: gradle/actions/setup-gradle@v4
+      - name: Set up Android SDK
+        run: |
+          echo "Accepting all SDK licenses"
+          yes | sdkmanager --licenses || true
 
-      - name: Create AVD and generate snapshot for caching
-        if: steps.avd-cache.outputs.cache-hit != 'true'
+          echo "Installing required SDK components"
+          sdkmanager --install \
+            "build-tools;35.0.0" \
+            "platform-tools" \
+            "platforms;android-31" \
+            "emulator" \
+            "system-images;android-31;default;arm64-v8a" \
+            --channel=0 || true
+        shell: bash
+
+      - name: Get device name
+        id: device
+        run: node -e "console.log('AVD_NAME=' + require('./.detoxrc.js').devices.emulator.device.avdName)" >> $GITHUB_OUTPUT
+
+      - name: Start Android Emulator
         uses: reactivecircus/android-emulator-runner@v2
         with:
           api-level: ${{ env.API_LEVEL }}
           arch: ${{ env.ARCH }}
-          disable-animations: false
-          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
-          force-avd-creation: false
-          script: echo 'Generated AVD snapshot for caching.'
+          avd-name: ${{ steps.device.outputs.AVD_NAME }}
+          emulator-boot-timeout: 300
+          script: echo 'Starting...'
+
+      # - name: Create AVD and generate snapshot for caching
+      #   if: steps.avd-cache.outputs.cache-hit != 'true'
+      #   uses: reactivecircus/android-emulator-runner@v2
+      #   with:
+      #     api-level: ${{ env.API_LEVEL }}
+      #     arch: ${{ env.ARCH }}
+      #     disable-animations: false
+      #     emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
+      #     force-avd-creation: false
+      #     script: echo 'Generated AVD snapshot for caching.'
 
       - name: Start Metro bundler
         run: yarn metro &
@@ -58,9 +83,9 @@ jobs:
       - name: Build Detox APK
         run: yarn detox:build:android:release
 
-      - name: Get device name
-        id: device
-        run: node -e "console.log('AVD_NAME=' + require('./.detoxrc.js').devices.emulator.device.avdName)" >> $GITHUB_OUTPUT
+      # - name: Get device name
+      #   id: device
+      #   run: node -e "console.log('AVD_NAME=' + require('./.detoxrc.js').devices.emulator.device.avdName)" >> $GITHUB_OUTPUT
 
       - name: Run Detox tests
         uses: reactivecircus/android-emulator-runner@v2
